remote_theme: b2a3e8/jekyll-theme-console

header_pages:
- index.md
- media.md
- posts.md
- contact.html

footer: <i>Site Ver. 1.0b3</i><br /><i>Copyright 2020 Lennon Incorporated</i>
listen_for_clients_preferred_style: false
