remote_theme: b2a3e8/jekyll-theme-console

header_pages:
- index.md
- media.md
- posts.md
- contact.html
- the-archive.html

footer: <i>Site Ver. 1.0b3 Last Update: 8/30/2020</i><br /><i>Copyright 2020 Lennon Incorporated</i>
listen_for_clients_preferred_style: false
